from typing import Any

class DatastoreStub:
    Lookup: Any = ...
    RunQuery: Any = ...
    BeginTransaction: Any = ...
    Commit: Any = ...
    Rollback: Any = ...
    AllocateIds: Any = ...
    ReserveIds: Any = ...
    def __init__(self, channel: Any) -> None: ...

class DatastoreServicer:
    def Lookup(self, request: Any, context: Any) -> None: ...
    def RunQuery(self, request: Any, context: Any) -> None: ...
    def BeginTransaction(self, request: Any, context: Any) -> None: ...
    def Commit(self, request: Any, context: Any) -> None: ...
    def Rollback(self, request: Any, context: Any) -> None: ...
    def AllocateIds(self, request: Any, context: Any) -> None: ...
    def ReserveIds(self, request: Any, context: Any) -> None: ...

def add_DatastoreServicer_to_server(servicer: Any, server: Any) -> None: ...
