# Names in __all__ with no definition:
#   AllocateIdsRequest
#   AllocateIdsResponse
#   ArrayValue
#   BeginTransactionRequest
#   BeginTransactionResponse
#   BoolValue
#   BytesValue
#   CommitRequest
#   CommitResponse
#   CompositeFilter
#   CustomHttpPattern
#   DescriptorProto
#   DoubleValue
#   Entity
#   EntityResult
#   EnumDescriptorProto
#   EnumOptions
#   EnumValueDescriptorProto
#   EnumValueOptions
#   ExtensionRangeOptions
#   FieldDescriptorProto
#   FieldOptions
#   FileDescriptorProto
#   FileDescriptorSet
#   FileOptions
#   Filter
#   FloatValue
#   GeneratedCodeInfo
#   GqlQuery
#   GqlQueryParameter
#   Http
#   HttpRule
#   Int32Value
#   Int64Value
#   Key
#   KindExpression
#   LatLng
#   ListValue
#   LookupRequest
#   LookupResponse
#   MessageOptions
#   MethodDescriptorProto
#   MethodOptions
#   Mutation
#   MutationResult
#   OneofDescriptorProto
#   OneofOptions
#   PartitionId
#   Projection
#   PropertyFilter
#   PropertyOrder
#   PropertyReference
#   Query
#   QueryResultBatch
#   ReadOptions
#   ReserveIdsRequest
#   ReserveIdsResponse
#   RollbackRequest
#   RollbackResponse
#   RunQueryRequest
#   RunQueryResponse
#   ServiceDescriptorProto
#   ServiceOptions
#   SourceCodeInfo
#   StringValue
#   Struct
#   Timestamp
#   TransactionOptions
#   UInt32Value
#   UInt64Value
#   UninterpretedOption
#   Value
#   Value
