import enum

class NullValue(enum.IntEnum):
    NULL_VALUE: int = ...

class CommitRequest:
    class Mode(enum.IntEnum):
        MODE_UNSPECIFIED: int = ...
        TRANSACTIONAL: int = ...
        NON_TRANSACTIONAL: int = ...

class CompositeFilter:
    class Operator(enum.IntEnum):
        OPERATOR_UNSPECIFIED: int = ...
        AND: int = ...

class EntityResult:
    class ResultType(enum.IntEnum):
        RESULT_TYPE_UNSPECIFIED: int = ...
        FULL: int = ...
        PROJECTION: int = ...
        KEY_ONLY: int = ...

class PropertyFilter:
    class Operator(enum.IntEnum):
        OPERATOR_UNSPECIFIED: int = ...
        LESS_THAN: int = ...
        LESS_THAN_OR_EQUAL: int = ...
        GREATER_THAN: int = ...
        GREATER_THAN_OR_EQUAL: int = ...
        EQUAL: int = ...
        HAS_ANCESTOR: int = ...

class PropertyOrder:
    class Direction(enum.IntEnum):
        DIRECTION_UNSPECIFIED: int = ...
        ASCENDING: int = ...
        DESCENDING: int = ...

class QueryResultBatch:
    class MoreResultsType(enum.IntEnum):
        MORE_RESULTS_TYPE_UNSPECIFIED: int = ...
        NOT_FINISHED: int = ...
        MORE_RESULTS_AFTER_LIMIT: int = ...
        MORE_RESULTS_AFTER_CURSOR: int = ...
        NO_MORE_RESULTS: int = ...

class ReadOptions:
    class ReadConsistency(enum.IntEnum):
        READ_CONSISTENCY_UNSPECIFIED: int = ...
        STRONG: int = ...
        EVENTUAL: int = ...
