from google.cloud.datastore import helpers as helpers
from typing import Any

class Batch:
    _id: Any = ...
    _INITIAL: int = ...
    _IN_PROGRESS: int = ...
    _ABORTED: int = ...
    _FINISHED: int = ...
    _client: Any = ...
    _mutations: Any = ...
    _partial_key_entities: Any = ...
    _status: Any = ...
    def __init__(self, client: Any) -> None: ...
    def current(self): ...
    @property
    def project(self): ...
    @property
    def namespace(self): ...
    def _add_partial_key_entity_pb(self): ...
    def _add_complete_key_entity_pb(self): ...
    def _add_delete_key_pb(self): ...
    @property
    def mutations(self): ...
    def put(self, entity: Any) -> None: ...
    def delete(self, key: Any) -> None: ...
    def begin(self) -> None: ...
    def _commit(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

def _assign_entity_to_pb(entity_pb: Any, entity: Any) -> None: ...
def _parse_commit_response(commit_response_pb: Any): ...
