from google.cloud._helpers import _ensure_tuple_or_list as _ensure_tuple_or_list
from typing import Any, Optional

class Entity(dict):
    key: Any = ...
    exclude_from_indexes: Any = ...
    _meanings: Any = ...
    def __init__(
        self, key: Optional[Any] = ..., exclude_from_indexes: Any = ...
    ) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    @property
    def kind(self): ...
    @property
    def id(self): ...
    def __repr__(self): ...
