from google.cloud.datastore_v1.proto import datastore_pb2_grpc as datastore_pb2_grpc
from typing import Any, Optional

class DatastoreGrpcTransport:
    def __init__(self, channel: Optional[Any] = ..., credentials: Optional[Any] = ..., address: str = ...) -> None: ...
    @classmethod
    def create_channel(cls, address: str = ..., credentials: Optional[Any] = ..., **kwargs: Any): ...
    @property
    def channel(self): ...
    @property
    def lookup(self): ...
    @property
    def run_query(self): ...
    @property
    def begin_transaction(self): ...
    @property
    def commit(self): ...
    @property
    def rollback(self): ...
    @property
    def allocate_ids(self): ...
    @property
    def reserve_ids(self): ...
