name: CI

on: [push, pull_request]

jobs:
  tox-meta:
    name: Run ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['lint', 'typecheck']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.task }}

  py-tests:
    name: Run Tests - Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip install tox
      - name: Run Tox
        run: tox -e py
